spring.application.name=gestion-notification
server.port=8086
# Configuration SMTP pour l'envoi des emails (exemple avec Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarrabenhamouda7@gmail.com
spring.mail.password=wwjy sgfa qlxk wixf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Configuration Twilio (SMS
twilio.account.sid=AC598648916f45aeffbf7e9a4c7d1ca1d9
twilio.auth.token=9cf2daf83dee628888dae9f5a893d7fc
twilio.phone.number=+17622247317
# Datasource
spring.datasource.url=jdbc:h2:mem:gestionNotification;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

#eureka
eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=20
#config server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888
