spring.application.name=GestionPaie
server.port=8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amiriakenza08@gmail.com
spring.mail.password=zsdm ajfe qllu grhy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:h2:mem:gestionPaie;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=20

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/myrealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/myrealm/protocol/openid-connect/certs


logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.server=DEBUG
logging.level.com.example=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR


# Emplacement du fichier de logs
logging.file.name=logs/gestion-paie.log
